spring:
  data:
    mongodb:
      database: dog-vote
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
  paths-to-match:
    - /dogs/**
    - /votes/**